use_frameworks!
platform :ios, '10.0'
target 'SaePlayer_Example' do
  pod 'SaePlayer', :path => '../'
  pod 'SnapKit', '~> 4.2.0'
  target 'SaePlayer_Tests' do
    inherit! :search_paths

    
  end
end
